### ISSUE TITLE
AttributeError: 'IBKRCmdlineApp' object has no attribute 'order'

### ISSUE THREAD

**Issue by keyunluo** [mattsta/icli#12]
OS: Ubuntu 22.04
Python: 3.12

when run `poetry run icli` command:

```
2024-08-12 16:35:16.260 | ERROR    | icli.cli:reconnect:3316 - why?
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/data/jupyter/icli/icli/__main__.py", line 61, in runit
    asyncio.run(initcli())
    │       │   └ <function initcli at 0x70918cdde2a0>
    │       └ <function run at 0x70918c5313a0>
    └ <module 'asyncio' from '/usr/local/miniconda3/lib/python3.12/asyncio/__init__.py'>

  File "/usr/local/miniconda3/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           │      │   └ <coroutine object initcli at 0x70918cdd1b60>
           │      └ <function Runner.run at 0x70918c3e42c0>
           └ <asyncio.runners.Runner object at 0x70918cf9b710>
  File "/usr/local/miniconda3/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<initcli() running at /data/jupyter/icli/icli/__main__.py:46> cb=[_run_until_complete_cb() a...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x70918c3d9ee0>
           │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x70918cf9b710>
  File "/usr/local/miniconda3/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x70918c3d9e40>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/miniconda3/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x70918c3dbc40>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/miniconda3/lib/python3.12/asyncio/base_events.py", line 1985, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x70918c5320c0>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>
  File "/usr/local/miniconda3/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup(<Future finished result=None>)>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup(<Future finished result=None>)>

  File "/data/jupyter/icli/icli/__main__.py", line 46, in initcli
    await app.runall()
          │   └ <function IBKRCmdlineApp.runall at 0x7090e5aa4400>
          └ IBKRCmdlineApp(accountId='xxxxxx', toolbarUpdateInterval=3.33, host='xxxxxx', port=xxxxxx, clientId=0, isSandbox=None, ...

  File "/data/jupyter/icli/icli/cli.py", line 3127, in runall
    await self.prepare()
          │    └ <function IBKRCmdlineApp.prepare at 0x7090e5aa44a0>
          └ IBKRCmdlineApp(accountId='xxxxxx', toolbarUpdateInterval=3.33, host='xxxxxx', port=xxxxxx, clientId=0, isSandbox=None, ...

  File "/data/jupyter/icli/icli/cli.py", line 3325, in prepare
    await reconnect()
          └ <function IBKRCmdlineApp.prepare.<locals>.reconnect at 0x7090e5af85e0>

> File "/data/jupyter/icli/icli/cli.py", line 3254, in reconnect
    self.order.clear()
    └ IBKRCmdlineApp(accountId='xxxxxx', toolbarUpdateInterval=3.33, host='xxxxxx', port=xxxxxx, clientId=0, isSandbox=None, ...
```

**Comment by mattsta** [comment]
thanks for pointing that out. I missed committing that partial block removal when I was refactoring out some unused state trackers. Fixed now ✅

(for that one at least! I'm in the middle of a large multi-component rewrite/refactor so lots will be updated all at once after a little more testing)
